{
 "title": "Nmap Dashboard",
 "tags": [ "nmap" ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Hosts Up",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT time AS \"time\", COUNT(DISTINCT ip) AS \"value\" FROM hosts WHERE $__timeFilter(time) GROUP BY time ORDER BY time",
     "rawSql": "SELECT \n  time AS \"time\",\n  COUNT(DISTINCT ip) AS \"value\"\nFROM hosts\nWHERE time = (SELECT MAX(time) FROM hosts WHERE $__timeFilter(time))\n  AND $__timeFilter(time)\nGROUP BY time;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Operating Systems",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "    \nSELECT\n  os,\n  COUNT(*) AS \"count\"\nFROM hosts\nWHERE start_time >= $__from AND end_time < $__to\nGROUP BY os\nORDER BY count DESC;\n\n    \n",
     "rawQueryText": "    \nSELECT\n  os,\n  COUNT(*) AS \"count\"\nFROM hosts\nWHERE start_time >= $__from AND end_time < $__to\nGROUP BY os\nORDER BY count DESC;\n\n    \n",
     "rawSql": "SELECT\n  os,\n  COUNT(DISTINCT ip) AS \"count\"\nFROM hosts\nWHERE $__timeFilter(time)\nGROUP BY os\nORDER BY count DESC;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Unidentified Services (open port)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT p.port, COUNT(*) AS count\nFROM ports p\nJOIN hosts h ON p.host_id = h.id\nWHERE h.start_time >= $__from AND h.end_time < $__to\n AND p.service_info = '' AND p.state = 'open'\nGROUP BY p.port",
     "rawQueryText": "SELECT p.port, COUNT(*) AS count\nFROM ports p\nJOIN hosts h ON p.host_id = h.id\nWHERE h.start_time >= $__from AND h.end_time < $__to\n AND p.service_info = '' AND p.state = 'open'\nGROUP BY p.port",
     "rawSql": "SELECT\n  p.port,\n  COUNT(DISTINCT h.ip) AS \"count\"\nFROM\n  ports p\n  JOIN hosts h ON p.host_id = h.id\nWHERE\n  $__timeFilter(h.time)\n  AND p.service_info = ''\n  AND p.state = 'open'\nGROUP BY\n  p.port\nORDER BY\n  count DESC;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Identified Services",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT p.service_info, COUNT(*) AS count\nFROM ports p\nJOIN hosts h ON p.host_id = h.id\nWHERE h.start_time >= $__from AND h.end_time < $__to\nAND p.service_info IS NOT NULL AND p.service_info <> ''\nGROUP BY p.service_info\n",
     "rawQueryText": "SELECT p.service_info, COUNT(*) AS count\nFROM ports p\nJOIN hosts h ON p.host_id = h.id\nWHERE h.start_time >= $__from AND h.end_time < $__to\nAND p.service_info IS NOT NULL AND p.service_info <> ''\nGROUP BY p.service_info\n",
     "rawSql": "SELECT\n  p.service_info,\n  COUNT(DISTINCT h.ip) AS count\nFROM ports p\nJOIN hosts h ON p.host_id = h.id\nWHERE $__timeFilter(h.time)\n  AND p.service_info IS NOT NULL\nGROUP BY p.service_info\nORDER BY count DESC;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Open Ports",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT SUM(unique_open_ports) AS total_unique_open_ports\nFROM (\n  SELECT\n    COUNT(DISTINCT p.port) AS unique_open_ports,\n    h.ip AS host_ip\n  FROM ports p\n  JOIN hosts h ON p.host_id = h.id\n  WHERE p.state = 'open' AND h.start_time >= $__from AND h.end_time < $__to\n  GROUP BY h.ip, p.port\n) AS subquery;\n    ",
     "rawQueryText": "SELECT SUM(unique_open_ports) AS total_unique_open_ports\nFROM (\n  SELECT\n    COUNT(DISTINCT p.port) AS unique_open_ports,\n    h.ip AS host_ip\n  FROM ports p\n  JOIN hosts h ON p.host_id = h.id\n  WHERE p.state = 'open' AND h.start_time >= $__from AND h.end_time < $__to\n  GROUP BY h.ip, p.port\n) AS subquery;\n    ",
     "rawSql": "WITH unique_ports AS (\n  SELECT\n    h.time,\n    h.ip,\n    COUNT(DISTINCT p.port) AS unique_open_ports\n  FROM\n    ports p\n    JOIN hosts h ON p.host_id = h.id\n  WHERE\n    p.state = 'open'\n    AND $__timeFilter(h.time)\n  GROUP BY\n    h.time,\n    h.ip\n),\nlatest_time AS (\n  SELECT MAX(time) AS max_time FROM unique_ports\n)\nSELECT\n  up.time AS \"time\",\n  SUM(up.unique_open_ports) AS \"value\"\nFROM unique_ports up\nJOIN latest_time lt ON up.time = lt.max_time\nGROUP BY up.time;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Unique Ports",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  COUNT(DISTINCT p.port) AS \"Unique Ports\"\nFROM ports p\nJOIN hosts h ON p.host_id = h.id\nWHERE h.start_time >= $__from AND h.end_time < $__to AND p.state is 'open'\n",
     "rawQueryText": "SELECT\n  COUNT(DISTINCT p.port) AS \"Unique Ports\"\nFROM ports p\nJOIN hosts h ON p.host_id = h.id\nWHERE h.start_time >= $__from AND h.end_time < $__to AND p.state is 'open'\n",
     "rawSql": "WITH latest_time AS (\n  SELECT MAX(date_trunc('second', h.time)) AS max_time\n  FROM hosts h\n  WHERE $__timeFilter(h.time)\n)\nSELECT\n  date_trunc('second', h.time) AS \"time\",\n  COUNT(DISTINCT p.port) AS \"value\"\nFROM ports p\nJOIN hosts h ON p.host_id = h.id\nJOIN latest_time lt ON date_trunc('second', h.time) = lt.max_time\nWHERE p.state = 'open'\n  AND $__timeFilter(h.time)\nGROUP BY 1\nORDER BY 1;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Open Ports Found",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 10, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "SELECT\n  p.port,\n  COUNT(DISTINCT h.ip) AS host_count\nFROM\n  hosts h\n  JOIN ports p ON h.id = p.host_id\nWHERE\n  p.state = 'open' AND h.start_time >= $__from AND h.end_time < $__to\nGROUP BY\n  p.port;",
     "rawQueryText": "SELECT\n  p.port,\n  COUNT(DISTINCT h.ip) AS host_count\nFROM\n  hosts h\n  JOIN ports p ON h.id = p.host_id\nWHERE\n  p.state = 'open' AND h.start_time >= $__from AND h.end_time < $__to\nGROUP BY\n  p.port;",
     "rawSql": "SELECT\n  p.port,\n COUNT(DISTINCT h.ip) AS host_count\nFROM hosts h\nJOIN ports p ON h.id = p.host_id\nWHERE p.state = 'open'\n  AND $__timeFilter(h.time)\nGROUP BY p.port",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Scans",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n  COUNT(*) AS count FROM scansWHERE  start_time >= $__from / 1000  AND start_time + elapsed_time < $__to / 1000",
     "rawQueryText": "SELECT\n  COUNT(*) AS count\nFROM scans\nWHERE\n  start_time >= $__from / 1000\n  AND start_time + elapsed_time < $__to / 1000",
     "rawSql": "SELECT\n  NULL AS \"time\",\n  COUNT(*) AS \"value\"\nFROM scans\nWHERE $__timeFilter(start_time);\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Hosts",
   "type": "table",
   "gridPos": { "h": 15, "w": 15, "x": 0, "y": 12 },
   "targets": [
    {
     "queryText": "SELECT ip, hostname, ports_tested, ports_open, ports_closed, ports_filtered FROM hosts\nWHERE start_time >= $__from AND end_time < $__to",
     "rawQueryText": "SELECT ip, hostname, ports_tested, ports_open, ports_closed, ports_filtered FROM hosts\nWHERE start_time >= $__from AND end_time < $__to",
     "rawSql": "SELECT DISTINCT ON (ip)\n  ip,\n  hostname,\n  ports_tested,\n  ports_open,\n  ports_closed,\n  ports_filtered,\n  time\nFROM hosts\nWHERE $__timeFilter(time)\nORDER BY ip, time DESC;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Live Hosts and Open Ports over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 12 },
   "targets": [
    {
     "queryText": "SELECT\n  start_time AS \"time\",\n  total_open_ports AS \"open_ports\",\n  total_hosts\nFROM scans\nWHERE\n  start_time >= $__from / 1000\n  AND start_time + elapsed_time < $__to / 1000\nORDER BY start_time",
     "rawQueryText": "SELECT\n  start_time AS \"time\",\n  total_open_ports AS \"open_ports\",\n  total_hosts\nFROM scans\nWHERE\n  start_time >= $__from / 1000\n  AND start_time + elapsed_time < $__to / 1000\nORDER BY start_time",
     "rawSql": "WITH uniq_hosts AS (\n  SELECT\n    h.time,\n    h.ip,\n    MAX(h.ports_open) AS ports_open  -- если один ip повторяется, берём одно значение\n  FROM hosts h\n  WHERE $__timeFilter(h.time)\n  GROUP BY h.time, h.ip\n)\nSELECT\n  time AS \"time\",\n  COUNT(*) AS \"hosts\",\n  SUM(ports_open) AS \"open_ports\"\nFROM uniq_hosts\nGROUP BY time\nORDER BY time;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Port Tested Per Second by Host",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 18 },
   "targets": [
    {
     "queryText": "SELECT ip, \n       (ports_tested * 1.0) / ((end_time - start_time) / 1000) AS avg_ports_per_second\nFROM hosts\nWHERE start_time >= $__from AND end_time < $__to AND ports_tested IS NOT NULL\nORDER BY ip;",
     "rawQueryText": "SELECT ip, \n       (ports_tested * 1.0) / ((end_time - start_time) / 1000) AS avg_ports_per_second\nFROM hosts\nWHERE start_time >= $__from AND end_time < $__to AND ports_tested IS NOT NULL\nORDER BY ip;",
     "rawSql": "SELECT DISTINCT ON (ip)\n  h.time           AS \"time\",\n  h.ports_tested   AS \"value\",\n  h.ip             AS \"host\"\nFROM hosts h\nWHERE $__timeFilter(h.time)\nORDER BY h.ip;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Open Services",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "queryText": "SELECT h.ip, p.protocol, p.port, p.service_info, p.http_title, p.ssl_common_name, p.ssl_issuer\nFROM ports p\nJOIN hosts h ON p.host_id = h.id\nWHERE h.start_time >= $__from AND h.end_time < $__to\nAND p.state = 'open'\n",
     "rawQueryText": "SELECT h.ip, p.protocol, p.port, p.service_info, p.http_title, p.ssl_common_name, p.ssl_issuer\nFROM ports p\nJOIN hosts h ON p.host_id = h.id\nWHERE h.start_time >= $__from AND h.end_time < $__to\nAND p.state = 'open'\n",
     "rawSql": "SELECT DISTINCT ON (h.ip, p.port)\n  h.time                 AS \"time\",\n  h.ip                   AS \"ip\",\n  p.protocol             AS \"protocol\",\n  p.port                 AS \"port\",\n  p.service_info         AS \"service_info\",\n  p.http_title           AS \"http_title\",\n  p.ssl_common_name      AS \"ssl_common_name\",\n  p.ssl_issuer           AS \"ssl_issuer\"\nFROM ports p\nJOIN hosts h ON p.host_id = h.id\nWHERE\n  p.state = 'open'\n  AND $__timeFilter(h.time)\nORDER BY h.ip, p.port, h.time DESC;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Scans Loaded",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "queryText": "SELECT\n  datetime(start_time, 'unixepoch') AS start_time_utc,\n  nmap_version,\n  command_line,\n  elapsed_time,\n  total_hosts,\n  total_open_ports\nFROM scans\nWHERE\n  start_time >= $__from / 1000\n  AND start_time + elapsed_time < $__to / 1000",
     "rawQueryText": "SELECT\n  datetime(start_time, 'unixepoch') AS start_time_utc,\n  nmap_version,\n  command_line,\n  elapsed_time,\n  total_hosts,\n  total_open_ports\nFROM scans\nWHERE\n  start_time >= $__from / 1000\n  AND start_time + elapsed_time < $__to / 1000",
     "rawSql": "SELECT\n  start_time                      AS \"time\",\n  nmap_version,\n  command_line,\n  elapsed_time,\n  total_hosts,\n  total_open_ports\nFROM scans\nWHERE $__timeFilter(start_time)\nORDER BY start_time;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}